name: credit_risk
version: "1.0.0"
config-version: 2
profile: credit_risk
model-paths: ["models"]
macro-paths: ["macros"]
models:
  credit_risk:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
